/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jgame.gradle.CircusCharlie;

import com.entropyinteractive.*; //jgame

import jgame.gradle.FontManager;
import jgame.gradle.CircusCharlie.ObjetosGraficos.Niveles.*;
import jgame.gradle.CircusCharlie.ObjetosGraficos.Obstaculos.Pelota;

import java.awt.*;
import java.awt.event.*; //eventos
import java.util.*;
import java.text.*;
public class CircusCharlie extends JGame {
    public final static int HEIGHT = 600;
    public final static int WIDTH = 800;
    public static boolean inicioNivel = false;
    Date dInit = new Date(), dAhora;
    SimpleDateFormat ft = new SimpleDateFormat("mm:ss");
    public static Camara cam;
    public static Fondo fondo;
    public static Charlie charlie;
    private static Nivel nivelActual;
    public static int nivel = 1;
    // Variables del level 1
    Nivel1 nivel1;
    public static Charlie leon;
    // Variables del level 2
    Nivel2 nivel2;
    // Variables del level 3
    Nivel3 nivel3;

    private int tempScore = 0;
    private double tempScoreX = 0;
    private double tempScoreY = 0;
    private long tempScoreStartTime = 0;
    private final long SCORE_DISPLAY_TIME = 1000; // tiempo en milisegundos que el puntaje se muestra en pantalla

    public static void main(String[] args) {
        CircusCharlie game = new CircusCharlie();
        game.run(1.0 / 60.0);
        System.exit(0);
    }

    public CircusCharlie() {
        // call game constructor
        super("AppCamaracharlie ", WIDTH, HEIGHT);
    }

    public void gameStartup() {
        Log.info(getClass().getSimpleName(), "Starting up game");
        Mundo m = Mundo.getInstance();
        try {
            if(nivelActual == null){
                nivelActual = new Nivel2(this);
            }
            cam.setRegionVisible(getWidth(), 480);
            m.setLimitesMundo(fondo.getWidth(), fondo.getHeight());
        } catch (Exception ex) {
            System.out.println("ERROR en gameStartup");
            ex.printStackTrace();
        }
    }
    public static void setFondo(Fondo fondo){
        CircusCharlie.fondo = fondo;
    }
    public static void setCamara(Camara camara){
        CircusCharlie.cam = camara;
    }
    public static void setCharlie(Charlie charlie){
        CircusCharlie.charlie = charlie;
    }
    public static void setLeon(Charlie leon){
        CircusCharlie.leon = leon;
    }

    public void gameUpdate(double delta) {
        
        if (!inicioNivel) {
            // FXPlayer.VICTORIA.stop();
            charlie.nivel(nivel);
            charlie.imagenNivel();
            
            Timer timer = new Timer();
            timer.schedule(new TimerTask() {
                @Override
                public void run() {
                    inicioNivel = true;
                }
            }, 3000);
            
        } else {
            if(!nivelActual.colisiono() && inicioNivel){
                nivelActual.gameUpdate(delta);
                if (nivelActual instanceof Nivel1) { // Aca va lo del nivel 1
                    Keyboard keyboard = getKeyboard();
                    if (keyboard.isKeyPressed(KeyEvent.VK_LEFT)) {
                        if (leon.getX() > 10 && Nivel1.llegoAMeta() == false) {
                            charlie.left();
                            if(!charlie.saltando()){
                                charlie.cambioImagen();
                            }
                            leon.leftLeon();
                        }
                    }
                    if (keyboard.isKeyPressed(KeyEvent.VK_RIGHT)) {
                        if (leon.getX() + leon.getWidth() < fondo.getWidth() && Nivel1.llegoAMeta() == false) {
                            charlie.right();
                            if(!charlie.saltando()){
                                charlie.cambioImagen();
                            }
                            leon.rightLeon();
                        }
                    }
                    if (keyboard.isKeyPressed(KeyEvent.VK_Z)) {
                        charlie.setPosition(7400 + 174, charlie.getY());
                        leon.setPosition(7400 + 143, leon.getY());
                    }
                    // check the list of key events for a pressed escape key
                    LinkedList<KeyEvent> keyEvents = keyboard.getEvents();
                    for (KeyEvent event : keyEvents) {
                        if ((event.getID() == KeyEvent.KEY_RELEASED)) {
                            charlie.quieto();
                            leon.quietoLeon();
                        }
                        if ((event.getID() == KeyEvent.KEY_PRESSED) && (event.getKeyCode() == KeyEvent.VK_SPACE)) {
                            if (Nivel1.llegoAMeta() == false) {
                                charlie.jump();
                                leon.jumpLeon();
                                FXPlayer.FX00.play();
                            }
                        }
                        if ((event.getID() == KeyEvent.KEY_PRESSED) && (event.getKeyCode() == KeyEvent.VK_ESCAPE)) {
                            FXPlayer.EVENTO1.stop();
                            stop();
                        }
                    }
                    leon.update(delta);
                    charlie.update(delta);
                    cam.seguirPersonaje(charlie,143); /// la camara sigue al Personaje
                    cam.seguirPersonaje(leon,143);
                }
                if (nivelActual instanceof Nivel2) { // Aca va lo del nivel 2
                    Keyboard keyboard = getKeyboard();
                    if (keyboard.isKeyPressed(KeyEvent.VK_LEFT)) {
                        if (charlie.getX() > 10){
                            charlie.left();
                            charlie.cambioImagen2();
                        }
                    }
                    if (keyboard.isKeyPressed(KeyEvent.VK_RIGHT)) {
                        if (charlie.getX() + charlie.getWidth() < fondo.getWidth() && !Nivel2.llegoAMeta()) {
                            charlie.right();
                            charlie.cambioImagen1();
                        }
                    }
                    if (keyboard.isKeyPressed(KeyEvent.VK_Z)) {
                        charlie.setPosition(5000 + 174, charlie.getY());
                    }
                    // check the list of key events for a pressed escape key
                    LinkedList<KeyEvent> keyEvents = keyboard.getEvents();
                    for (KeyEvent event : keyEvents) {
                        if ((event.getID() == KeyEvent.KEY_RELEASED)) {
                            charlie.quieto();
                        }
                        if ((event.getID() == KeyEvent.KEY_PRESSED) && (event.getKeyCode() == KeyEvent.VK_SPACE)) {
                            if (Nivel2.llegoAMeta() == false) {
                                charlie.jump();
                                FXPlayer.FX00.play();
                            }
                        }
                        if ((event.getID() == KeyEvent.KEY_PRESSED) && (event.getKeyCode() == KeyEvent.VK_ESCAPE)) {
                            FXPlayer.EVENTO1.stop();
                            stop();
                        }
                        
                    }
                    charlie.update(delta);
                    cam.seguirPersonaje(charlie,180); /// la camara sigue al Personaje
                }
                if (nivelActual instanceof Nivel3) { // Aca va lo del nivel 3
                    Keyboard keyboard = getKeyboard();
                    Pelota pelotaActual = Nivel3.getPelotaEnLaQueEstaParadoCharlie(charlie); // Obtén la pelota actual en la que está Charlie
                    // Movimiento de Charlie hacia la izquierda y la derecha
                    if (keyboard.isKeyPressed(KeyEvent.VK_LEFT) && !Nivel3.llegoAMeta()) {
                        if (charlie.getX() > 10) {
                            charlie.left();
                            charlie.cambioImagen2();
                            if (charlie.getEnLaPelota() && pelotaActual != null) {
                                pelotaActual.left();
                                pelotaActual.update(delta);
                            }
                        }
                    }
                    if (keyboard.isKeyPressed(KeyEvent.VK_RIGHT) && !Nivel3.llegoAMeta()) {
                        if (charlie.getX() + charlie.getWidth() < fondo.getWidth()) {
                            charlie.right();
                            charlie.cambioImagen1();
                            if (charlie.getEnLaPelota() && pelotaActual != null) {
                                pelotaActual.right();
                                pelotaActual.update(delta);
                            }
                        }
                    }
                
                    LinkedList<KeyEvent> keyEvents = keyboard.getEvents();
                    for (KeyEvent event : keyEvents) {
                        if (event.getID() == KeyEvent.KEY_RELEASED) {
                            charlie.quieto();
                        }
                        if (event.getID() == KeyEvent.KEY_PRESSED && event.getKeyCode() == KeyEvent.VK_SPACE) {
                            if (!Nivel3.llegoAMeta()) {
                                charlie.jump();
                                if (pelotaActual != null) {
                                    pelotaActual.setEstaMontado(false);
                                }
                                charlie.setEnLaPelota(false);
                                FXPlayer.FX00.play();
                            }
                        }
                        if (event.getID() == KeyEvent.KEY_PRESSED && event.getKeyCode() == KeyEvent.VK_ESCAPE) {
                            FXPlayer.EVENTO1.stop();
                            stop();
                        }
                    }
                    charlie.update(delta);
                    cam.seguirPersonaje(charlie,244); // la camara sigue al Personaje
                }
                // charlie.applyForce(gravedad);
            }
        }
    }

    public void gameDraw(Graphics2D g) {
        g.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        Mundo m = Mundo.getInstance();

        g.translate(cam.getX(), cam.getY());

        fondo.display(g);
        m.display(g);
        nivelActual.gameDraw(g);

        g.translate(-cam.getX(), -cam.getY());
        charlie.displayScore(g);
        g.setColor(Color.red);
        g.drawString("Tecla ESC = Fin del Juego ", 490, 20);

        displayTempScore(g);
    }

    public void gameShutdown() {
        // Log.info(getClass().getSimpleName(), "Shutting down game");
    }

    public static void changeState(Nivel state){
        CircusCharlie.nivelActual = state;
    }

    public void displayTempScore(Graphics2D g){
        FontManager.getInstance();
        if(tempScoreStartTime > 0){
            long currentTime = System.currentTimeMillis();
            if(currentTime - tempScoreStartTime < SCORE_DISPLAY_TIME){ 
                g.setColor(Color.WHITE);
                g.setFont(new Font("Pixel Emulator", Font.BOLD,20));
                g.drawString("+" + tempScore, (int) tempScoreX, (int) tempScoreY);
            }else{
                tempScoreStartTime = 0;
            }
        }
    }

    public void setTempScore(int score, double x, double y){
        this.tempScore = score;
        this.tempScoreX = x;
        this.tempScoreY = y;
        this.tempScoreStartTime = System.currentTimeMillis();
    }

    public static void inicioNivel(boolean b){
        CircusCharlie.inicioNivel = b;
    }

    public static void setNivel(int nivelSiguiente){
        CircusCharlie.nivel = nivelSiguiente;
    }
    public static int getNivel(){
        return nivel;
    }
}